use_frameworks!
platform :ios, '8.0'

target 'VSTwitterTextCounter_Example' do
  pod 'VSTwitterTextCounter', :path => '../'

  target 'VSTwitterTextCounter_Tests' do
    inherit! :search_paths


  end
end
